services:
  mysql:
    image: 'mysql:latest'
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - 'MYSQL_DATABASE=db_teste'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=secret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3308:3306'
