spring:
  sql:
    init:
      platform: h2
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:file:./biblioteca_api'
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  logging:
    level:
      org:
        springframework:
          test:
            web:
              reactive:
                server:
                  ExchangeResult=DEBUG: